### ISSUE TITLE
waypoint

### ISSUE THREAD

**Issue by jztmanyl** [Naxanria/Mappy#1]
How do I set a waypoint?

**Comment by Naxanria** [comment]
Not yet, its a planned feature.

**Comment by ThatGravyBoat** [comment]
Addition to this enhancement, death waypoints a waypoint that auto summons to where you died to and when in 4 block radius of it, it would auto delete the waypoint.

**Comment by Naxanria** [comment]
Waypoints are now implemented. since 0.0.12a
