### ISSUE TITLE
Log spam when loading skin + freezes

### ISSUE THREAD

**Issue by rinart73** [Naxanria/Mappy#12]
Minecraft: 1.14.4
Fabric: 0.4.8 build 159
Mod version: 1.0.1

I was playing multiplayer with another person and we both had freezes each second.
I looked at logs and saw this:
```
[00:09:04] [main/INFO]: [STDOUT]: Loading player head icon for Buisqwit
[00:09:04] [main/INFO]: [STDOUT]: Loading cached skin for Buisqwit
```
repeated over and over.

So I guess there are 2 issues:

1. Log spam
2. Loading skin and head icon should not happen each time?

**Comment by Naxanria** [comment]
Fixed in fabric-1.0.2
