### ISSUE TITLE
Crash with forge server

### ISSUE THREAD

**Issue by ghost** [Naxanria/Mappy#13]
When I try to start the server, this crash appears and I have to remove the mod to proceed.

https://pastebin.com/TArrkmCp

**Comment by Naxanria** [comment]
Mappy is client only, and should never be added to the server.

**Comment by MelanX** [comment]
but if you wanna play with mappy on a server you need it on server side, too
If I only install it in my client it says this:
![image](https://user-images.githubusercontent.com/26039509/66742065-1c032d80-ee77-11e9-9852-6d0a5e9d7906.png)

**Comment by Naxanria** [comment]
You can ignore that message. You can join without it having Mappy on the server.
