### ISSUE TITLE
[question/request] Mappy for Fabric

### ISSUE THREAD

**Issue by Bulldog83** [Naxanria/Mappy#19]
Hello! I've used your code from GitHub for updating mod. But I've fully removed entity radar and make some improvements. I've added icon for waypoint markers, made color extraction from textures, made map scaling and some features more. You can look at code here: https://github.com/Bulldog83/Mappy.
If you have no plans to update the mod for the Fabric, maybe you will not mind if I start a new project on the Curse? With reference to yours, of course.

**Comment by Naxanria** [comment]
I will not update it for fabric. Forge will be main focus.
And yes, I do mind if you would release it on curse, you do not have permission to do that.
