### ISSUE TITLE
Death Waypoints

### ISSUE THREAD

**Issue by Naxanria** [Naxanria/Mappy#8]
Waypoints automatically created on death, and removed when close.
With a different icon.

**Comment by ErdbeerbaerLP** [comment]
I already tried to implement them in 0.0.10a, but it is pretty difficult (especially detecting the death), if you want to see what i did, look there: https://github.com/ErdbeerbaerLP/Mappy
(I also added 2 language files while doing that)

**Comment by Naxanria** [comment]
Fixed in https://github.com/Naxanria/Mappy/commit/b5380de6e61e20a5032185306335ee85eec92e87
